### ISSUE TITLE
Can't check and uncheck updates

### ISSUE THREAD

**Issue by aeichepdx** [PDXostc/rvi_backend#19]
Clicking on checkboxes does not toggle checkbox.

![sota_admin](https://cloud.githubusercontent.com/assets/6910972/7642024/96ce2fe8-fa42-11e4-8b11-67ce19f8f5bc.PNG)

**Comment by bharmon** [comment]
Fixed in the commit "Fixed checkboxes CSS bug", Change-Id: Ie962c56c388102c37dc4b9fa9913ee69db795b63

**Comment by rstreif** [comment]
Pulled it onto the RVI1 server. It's working now.

On Thu, May 14, 2015 at 2:16 PM, Barbara Harmon <notifications@github.com>
wrote:

> Fixed in the commit "Fixed checkboxes CSS bug", Change-Id:
> Ie962c56c388102c37dc4b9fa9913ee69db795b63
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDXostc/rvi_backend/issues/19#issuecomment-102171407>.
>



-- 
*Rudolf J Streif*
System Architect - Open Source Initiative
Open Source Technology Centre

*M:* +1.858.583.1683
*Email:*  rstreif@jaguarlandrover.com



UK: G/26/2 G02 Building 523, Engineering Centre, Gaydon, Warwick, CV35 ORR
US: 1419 NW 14th Ave, Portland, OR 97209
jjaguar.com | landrover.com
-------------------
Business Details:
Jaguar Land Rover Limited
Registered Office: Abbey Road, Whitley, Coventry CV3 4LF
Registered in England No: 1672070

This e-mail and any attachments contain confidential information for a
specific individual and purpose.  The information is private and privileged
and intended solely for the use of the individual to whom it is addressed.
If you are not the intended recipient, please e-mail us immediately.  We
apologise for any inconvenience caused but you are hereby notified that any
disclosure, copying or distribution or the taking of any action in reliance
on the information contained herein is strictly prohibited.

This e-mail does not constitute an order for goods or services unless
accompanied by an official purchase order.

**Comment by aeichepdx** [comment]
Thanks!
